server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: file:C:\\\personal\\Microservicios store - copia\\\config-data
          #searchPaths: config-data
          #username: ${GIT_USER}
          #password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t